- __mocks__/i18next.js
- libs/clipboard/src/Clipboard.spec.tsx
- libs/clipboard/src/Clipboard.tsx
- libs/clipboard/src/i18n/constants.ts
- libs/clipboard/src/i18n/index.ts
- libs/clipboard/src/i18n/locales/en.ts
- libs/clipboard/src/i18n/locales/zh.ts
- libs/clipboard/src/index.ts
> feat(Clipboard): show default message when there is no onCopy property

- libs/forms/src/FormItemWrapper.module.css
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
Closes UISIX-10
请勾选以下两组选项其中之一：
或者：
>
>
表单项的附加信息是使用helpBrick来实现的，设计师希望在不使用usebrick情况下可以简单设置附加的说明信息，并且有个统一的默认样式。
> feat(forms): 表单支持简单说明

- libs/permission-utils/src/components/CommonSetting.tsx
> fix(permissions): 合并两个setState

- .size-limit.js
- __mocks__/@fortawesome/react-fontawesome.js
- libs/forms/src/components/icon-select/IconSelect.module.css
- libs/forms/src/components/icon-select/IconSelect.spec.tsx
- libs/forms/src/components/icon-select/IconSelect.tsx
- libs/forms/src/components/index.ts
- libs/forms/src/i18n/constants.ts
- libs/forms/src/i18n/locales/en.ts
- libs/forms/src/i18n/locales/zh.ts
- libs/forms/src/index.ts
> chore(): icon-select migrate to next-libs

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 用户没有主机实例操作权限， 安装redis点击从CMDB筛选主机会报错问题修复 Closed CD-1590

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
> chore(cmdb-instances-select-panel): 增加选择实例和表格间距

- libs/storyboard-visualization/src/RoutesGraph/RoutesPreview.tsx
> fix(): fix multiple HTML5 Backends error

- libs/forms/src/FormItemElement.ts
> chore(): property doc

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(instance): 实例列表默认pageSize

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
> fix(cmdb): tags添加allowClear

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
refs INSTANCE-1545
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instance): 输入框需要添加placeholder

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
refs INSTANCE-1545
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instance): 输入框需要placeholder提示错误

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs BRICK_STORE-2047
请勾选以下两组选项其中之一：
或者：
>
>
在请求cmdb接口之前，把请求参数对外暴露出去，供编排使用（例如instance-export构件，通过query参数来查询并导出列表中的实例）
> feat(cmdb-instances): 实例列表构件支持read.query.execute事件

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.spec.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
refs INSTANCE-1545
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instance): modify ModelAttributeFormControl placeholder

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/processors.spec.ts
- libs/cmdb-instances/src/processors.ts
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
fixes INSTANCE-1554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 修复instance-create中结构体的时间属性异常显示invalid date的问题

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
> fix(cmdb): fix筛选条件为整型时关闭不了bug

- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
fixes INSTANCE-1554
请勾选以下两组选项其中之一：
或者：
>
>
>    fix(cmdb-instances): 修复instance-edit中结构体的时间属性异常显示invalid date的问题

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list-table/utils.spec.ts
- libs/cmdb-instances/src/instance-list-table/utils.ts
> fix(cmdb): 主机列表内存,cpu频率,磁盘单位转换

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
fixes INSTANCE-1571
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 实例列表切换页码无效且重复请求的问题

- libs/forms/src/components/icon-select/IconSelect.spec.tsx
- libs/forms/src/components/icon-select/IconSelect.tsx
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> feat(icon-select): defaultColor

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.spec.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
- libs/cmdb-instances/src/struct-components/StructTable.tsx
- libs/cmdb-instances/src/struct-components/mockData.ts
refs INSTANCE-1581
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instance-edit): 结构体为浮点型未做校验&单结构体无法删除&markdown不支持编辑

- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> chore(instance-edit): add test

- libs/storyboard-visualization/src/RoutesGraph/RouteNodeComponent.tsx
- libs/storyboard-visualization/src/RoutesGraph/RoutesPreview.tsx
refs NEXT_BUILDER-751
请勾选以下两组选项其中之一：
或者：
>
>
> fix(route-preview): actionsVisible

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs CD-1671
请勾选以下两组选项其中之一：
或者：
>
>
> fix(InstanceList): fix sort

- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceDetail.spec.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbObjectDetail.spec.ts
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.spec.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
refs INSTANCE-1513
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instance-edit): 初始化bool为false的时候，回填失败

- libs/cmdb-instances/src/data-providers/fetchCmdbObjectList.spec.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbObjectRef.spec.ts
> chore(): add test

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs CD-1677
请勾选以下两组选项其中之一：
或者：
>
>
> fix(ModelAttributeForm): only reset form when continueCreating is true

- libs/forms/src/components/icon-select/IconSelect.tsx
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> fix(icon-select): reset color when defaultColor changes

- .size-limit.js
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs INSTANCE-1625
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 实例列表高级搜索接受的结构体数据和aq查询条件中的数据不一致

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs CD-1671
请勾选以下两组选项其中之一：
或者：
>
>
> fix(InstanceList): fix request data missed fields

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(InstanceList): page and pageSize state add default value

- libs/forms/src/components/icon-select/IconSelect.spec.tsx
- libs/forms/src/components/icon-select/IconSelect.tsx
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> fix(icon-select): set color when props.value changes

- libs/storyboard-visualization/src/RoutesGraph/RouteNodeComponent.tsx
- libs/storyboard-visualization/src/RoutesGraph/RouteTypeIcon.spec.tsx
- libs/storyboard-visualization/src/RoutesGraph/RouteTypeIcon.tsx
- libs/storyboard-visualization/src/RoutesGraph/RoutesGraph.module.css
- libs/storyboard-visualization/src/RoutesGraph/RoutesGraph.spec.tsx
- libs/storyboard-visualization/src/RoutesGraph/RoutesGraph.tsx
refs NEXT_BUILDER-777
请勾选以下两组选项其中之一：
或者：
>
>
> feat(route-graph): Automatically locate unlocated nodes

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-1639
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 高级搜索回填问题

- .npmrc
- .yarnrc
- yarn.lock
> chore(): use original npm registry

- .size-limit.js
- libs/svga/package.json
- libs/svga/src/index.ts
- libs/svga/src/svga-player/SvgaPlayer.tsx
Refs Refs USER_ADMIN-124
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): some optimization

- libs/svga/src/svga-player/SvgaPlayer.tsx
Refs USER_ADMIN-124
请勾选以下两组选项其中之一：
或者：
>
>
> fix():: clearsAfterStop default false

- libs/cmdb-utils/src/cmdbUtil.spec.ts
- libs/cmdb-utils/src/cmdbUtil.ts
refs INSTANCE-1644
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-utils): 自关联问题

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(InstanceListTable): fix pagination.current pass in 0

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list-table/MoreButtonsContainer.tsx
- libs/cmdb-instances/src/instance-list-table/SettingsContainer.tsx
refs INSTANCE-1644
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 自关联问题&显示字段的弹窗样式

- libs/datetime/src/humanizeTime.spec.ts
- libs/datetime/src/humanizeTime.ts
- libs/datetime/src/i18n/constants.ts
- libs/datetime/src/i18n/index.ts
- libs/datetime/src/i18n/locales/en.ts
- libs/datetime/src/i18n/locales/zh.ts
refs INSTANCE-1671
请勾选以下两组选项其中之一：
或者：
>
>
> feat(datetime): datetime 增加国际化

- libs/svga/src/svga-player/SvgaPlayer.tsx
Refs USER_ADMIN-124
请勾选以下两组选项其中之一：
或者：
>
>
> feat():: add onloaded event

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
refs CD-1794
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): form validate

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-1684
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 实例列表的高级搜索筛选“布尔型”数据时，无法清除筛选项

- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
refs INSTANCE-1719
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): modify i18n

- libs/forms/src/FormItemElement.ts
- libs/forms/src/FormItemWrapper.module.css
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
Closes UISIX-112
请勾选以下两组选项其中之一：
或者：
>
>
设计师期望能统一表单中使用tooltip的规范，在属性labelTooltip为字符串时应用这种规范样式。
https://lanhuapp.com/web/#/item/project/detailDetach?pid=4c331720-5b34-4b13-b023-d1b4a696a0bf&see=all&project_id=4c331720-5b34-4b13-b023-d1b4a696a0bf&image_id=ce775386-577a-4605-8c90-17fd90eaa3de&fromEditor=true
> feat(forms): labelTooltip支持string类型以便设置tooltip

- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
Closes UISIX-112
请勾选以下两组选项其中之一：
或者：
>
>
> chore(forms): 去掉label后的空格

- libs/forms/src/FormItemWrapper.module.css
- libs/forms/src/FormItemWrapper.tsx
Closes UISIX-112
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 修复label内容换行时，label内容排列不正常问题

- libs/datetime-components/src/datetime-range/DatetimeRange.spec.tsx
- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
- libs/datetime-components/src/i18n/constants.ts
- libs/datetime-components/src/i18n/index.ts
- libs/datetime-components/src/i18n/locales/en.ts
- libs/datetime-components/src/i18n/locales/zh.ts
Closes AUDIT-96
请勾选以下两组选项其中之一：
或者：
>
>
> feat(datetime-components): add i18n

- libs/forms/src/FormItemElement.ts
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
> feat(FormItemWrapper): add trim support

- libs/datetime/src/humanizeTime.spec.ts
- libs/datetime/src/humanizeTime.ts
- libs/datetime/src/i18n/locales/en.ts
- libs/datetime/src/i18n/locales/zh.ts
refs USER_ADMIN-150
请勾选以下两组选项其中之一：
或者：
>
>
> fix(datetime): modify i18n

- libs/cmdb-instances/src/struct-components/StructTable.tsx
- libs/cmdb-utils/src/processors/formatAttrValue.spec.ts
- libs/cmdb-utils/src/processors/formatAttrValue.ts
refs INSTANCE-1766
refs INSTANCE-1146
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 结构体信息展示异常

- .size-limit.js
- libs/basic-components/src/GeneralIcon.module.css
- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
Closes BRICK_STORE-2136
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-components): generalIcon增加round-square样式

- .size-limit.js
- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
- package.json
- yarn.lock
Closes EASY_HUB-170
请勾选以下两组选项其中之一：
或者：
>
>
> feat(gerenal-icon): 图标支持渐变色

- libs/cmdb-instances/src/i18n/locales/en.ts
refs INSTANCE-1772
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): add i18n

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 图标等更改 Closed BRICK_STORE-2143

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-1713
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 多次搜索为空的时候，query有误

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 图标样式调整 Closed BRICK_STORE-2143

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 单结构体图标样式 Closed EASY_WORK-429

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): field不存在字段时会报错 Closed EASYCORE-493

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/constants/index.ts
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): 详情编辑页的关系字段显示 INSTANCE-1808

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(): 关系字段显示逻辑调整 INSTANCE-1808

- libs/charts/src/utils/time.spec.ts
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): 新版页面，关闭用户某个属性视图后，前端页面仍能显示用户信息 closed INSTANCE-1805

- libs/charts/src/utils/data.spec.ts
- libs/cmdb-instances/src/components/instance-format/__snapshots__/index.spec.tsx.snap
- libs/cmdb-instances/src/components/instance-format/index.spec.tsx
- libs/cmdb-instances/src/components/instance-format/index.tsx
- libs/cmdb-instances/src/i18n/constants.ts
- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.spec.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
> feat(): 实例列表、详情、关系展示等页面兼容json格式 closed INSTANCE-1789

- libs/charts/src/utils/percent.spec.ts
- libs/cmdb-instances/src/components/instance-format/index.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
> fix(): 页面兼容json格式 closed INSTANCE-1789

- libs/cmdb-instances/src/components/instance-format/index.tsx
- libs/cmdb-instances/src/instance-attribute-form/InstanceAttributeForm.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
- libs/cmdb-instances/src/struct-components/StructTable.tsx
> fix(): json格式补充 closed INSTANCE-1789

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes EASY_HUB-246
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 有默认selectedRowKeys时拉取数据

- .size-limit.js
- __jest__/setup.ts
- libs/charts/src/utils/valueFormatter.spec.ts
- libs/cmdb-instances/package.json
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.spec.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
- libs/cmdb-instances/src/struct-components/mockData.ts
- libs/editor-components/package.json
- libs/editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/editor-components/src/code-editor/CodeEditor.tsx
- libs/editor-components/src/interfaces.ts
- yarn.lock
> fix(): json输入用代码输入框  closed INSTANCE-1817

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): cmdb实例列表添加属性控制查询条件的显示 closed FULLSEARCH-82

- libs/basic-components/src/Sidebar.spec.tsx
- libs/basic-components/src/Sidebar.tsx
refs BRICK_STORE-2188
请勾选以下两组选项其中之一：
或者：
>
>
> fix(basic-components): 折叠时，刷新页面菜单悬浮

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 添加onlySearchByIp属性让IP搜索仅搜索IP closed FULLSEARCH-82

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): 添加属性控制新建时白名单是否需要输入 closed INSTANCE-1829

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): 属性补充,用户组可选 closed INSTANCE-1829

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 当属性字段或关系字段的ID为children时，会有不同的报错 closed INSTANCE-1844

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix(): 实例弹窗透传应用筛选 closed INSTANCE-1834

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 实例弹窗切换应用筛选时屏蔽高级搜索 closed INSTANCE-1834

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 按应用筛选选择支持搜索所有 closed INSTANCE-1834

- .size-limit.js
- libs/crontab/src/format.spec.ts
- libs/crontab/src/format.ts
> chore(crontab): add i18n

- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-instances/src/struct-components/StructTable.tsx
> fix(): 关于新建编辑实例时结构体的各种问题 closed INSTANCE-1850

- libs/crontab/src/i18n/constants.ts
- libs/crontab/src/i18n/index.ts
- libs/crontab/src/i18n/locales/en.ts
- libs/crontab/src/i18n/locales/zh.ts
- libs/crontab/src/index.ts
> chore(): add i18n

- libs/basic-components/package.json
- libs/charts/package.json
- libs/clipboard/package.json
- libs/cmdb-instances/package.json
- libs/cmdb-tree/package.json
- libs/cmdb-utils/package.json
- libs/code-display-components/package.json
- libs/code-editor-components/package.json
- libs/constants/package.json
- libs/crontab/package.json
- libs/datetime-components/package.json
- libs/datetime/package.json
- libs/forms/package.json
- libs/hooks/package.json
- libs/permission-utils/package.json
- libs/searchable-tree/package.json
- libs/storage/package.json
- libs/storyboard-visualization/package.json
- libs/svga/package.json
- libs/visit-history/package.json
- package.json
- yarn.lock
Manually yarn renew by Github Actions.
> Yarn renew

- libs/code-editor-components/src/brace/index.ts
> fix(code-editor): add language of typescript

- libs/permission-utils/src/components/CommonSetting.tsx
> fix(permission-utils): fix删除用户时操作类型还是add bug

- __mocks__/brace/index.js
- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageMode.ts
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageRules.spec.ts
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageRules.ts
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageYamlMode.ts
- libs/code-editor-components/src/interfaces.ts
> feat(): support common expression language

- libs/permission-utils/src/components/SelectUserOrGroup.tsx
> fix(permission): fix user/usergroup filter bug

- libs/basic-components/src/GeneralIcon.tsx
- libs/basic-components/src/__snapshots__/Sidebar.spec.tsx.snap
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/components/icon-select/IconSelect.spec.tsx
> fix(general-icon): fix icon flicker

- libs/basic-components/src/ItemActionsComponent.spec.tsx
- libs/basic-components/src/ItemActionsComponent.tsx
- libs/basic-components/src/ItemActionsMenu.tsx
> fix(): fix ItemActionsComponent flicker

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.spec.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
fixes INSTANCE-1888
请勾选以下两组选项其中之一：
或者：
>
>
> fix(model-attribute-form): 修复结构体无属性字段,无枚举值时不应该整体报错的问题

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list/constants.ts
- libs/forms/src/message.ts
> feat(): add i18n refs INSTANCE-1903

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list-table/MoreButtonsContainer.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/cmdb-instances/src/instance-list/constants.ts
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/forms/src/message.ts
> feat(): add i18n refs INSTANCE-1883

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list-table/MoreButtonsContainer.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/cmdb-instances/src/instance-list/constants.ts
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/forms/src/message.ts
Reverts easyops-cn/next-libs#167
> Revert "feat(): add i18n refs INSTANCE-1883"

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageRules.ts
- libs/code-editor-components/src/interfaces.ts
> fix(): refine completers

- libs/permission-utils/src/components/BatchSetting.tsx
> fix(permission-utils): 删除白名单说明tooltip

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
> fix(): json输入框主题色 Closed INSTANCE-1859

- libs/cmdb-instances/src/i18n/locales/en.ts
> fix(): i18n Closed PERMISSION-178

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs MONITOR-2011
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): instance-list 右上角显示问题

- libs/code-editor-components/src/code-editor/CodeEditor.module.css
- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/code-editor/getClickableMarker.spec.ts
- libs/code-editor-components/src/code-editor/getClickableMarker.ts
- libs/code-editor-components/src/code-editor/getHighlightMarkers.spec.ts
- libs/code-editor-components/src/code-editor/getHighlightMarkers.ts
- libs/code-editor-components/src/interfaces.ts
BREAKING CHANGE: drop support for debounce selection change
请勾选以下两组选项其中之一：
或者：
>
>
> feat(code-editor): support to highlight tokens

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
Refs NEXT_BUILDER-971
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): editor add resizeObserver

- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
Refs
BRICK_STORE-2293
请勾选以下两组选项其中之一：
或者：
>
>
> feat(GeneralIcon): add data-icon attribute

- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
Refs: MONITOR-2140
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 图标判断逻辑问题,导致icon传空,无法选择图标的问题

- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
Refs: MONITOR-2140
请勾选以下两组选项其中之一：
或者：
>
>
icon-select 存在单独传入color的情况, 在之前逻辑对此情况没有做渲染处理, 此次pr专门修复该问题
> fix(): 支持单独颜色入参渲染情况

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.spec.tsx
- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
- libs/cmdb-instances/src/struct-components/interfaces.ts
- libs/cmdb-instances/src/struct-components/mockData.ts
Closes BRICK_STORE-2294
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 创建结构体弹窗改为使用form

- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
请勾选以下两组选项其中之一：
或者：
>
>
修复icon入参为string或number类型时, 渲染报错的问题
> fix(GeneralIcon): error while props.icon was number or string

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes INSTANCE-1932
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 修复实例列表高级搜索-关系字段查询回填不正确

- libs/cmdb-instances/package.json
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- yarn.lock
Closes INSTANCE-1941
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 实例列表自增id流水号属性排序使用自然排序

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs INSTANCE-1959
请勾选以下两组选项其中之一：
或者：
>
>
> chore(cmdb-instance): 关闭搜索实例来源tag

- libs/storyboard-visualization/src/RoutesGraph/processors/adoptLink.spec.ts
- libs/storyboard-visualization/src/RoutesGraph/processors/adoptLink.ts
> fix(routes-graph): handle when no adoptable link

- libs/cmdb-instances/src/cmdb-url-link/CmdbUrlLink.spec.tsx
- libs/cmdb-instances/src/cmdb-url-link/CmdbUrlLink.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
Closes INSTANCE-1998
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances):  实例列表，url 类型支持跳转功能

- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
refs INSTANCE-1942
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances):  删除结构体，提示不对

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs INSTANCE-1966
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances):  IP类型字段支持批量选择后复制所选IP

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
refs INSTANCE-1993
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 当数组不必填有正则的时候，不填的时候不触发校验正则

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/i18n/index.ts
> fix(): dashboard新建仪表盘--构件翻译失败 MONITOR-2122

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix(): 告警事件中心CMDB通用实例列表模态框v2弹窗的取消按钮应使用文字按钮样式 EVENT-275

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/cmdb-utils/src/processors/object.spec.ts
- libs/cmdb-utils/src/processors/object.ts
Refs INSTANCE-1970
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instance): 修复自关联模型只有一个字段

- libs/cmdb-instances/src/attribute-form-control-url/AttributeFormControlUrl.spec.tsx
- libs/cmdb-instances/src/attribute-form-control-url/AttributeFormControlUrl.tsx
Refs INSTANCE-2013
请勾选以下两组选项其中之一：
或者：
>
>
> chore(AttributeFormControlUrl):  自动填充域名

- libs/cmdb-instances/src/attribute-form-control-url/AttributeFormControlUrl.tsx
- libs/cmdb-instances/src/attribute-form-control-url/__snapshots__/AttributeFormControlUrl.spec.tsx.snap
Refs INSTANCE-2013
请勾选以下两组选项其中之一：
或者：
>
>
> chore(AttributeFormControlUrl):  自动填充域名（提交执行）

- libs/cmdb-instances/src/attribute-form-control-url/AttributeFormControlUrl.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs INSTANCE-2022
请勾选以下两组选项其中之一：
或者：
>
>
> fix(AttributeFormControlUrl):  修复编辑自动为null的问题

- libs/cmdb-instances/src/attribute-form-control-url/AttributeFormControlUrl.tsx
Refs INSTANCE-2022
请勾选以下两组选项其中之一：
或者：
>
>
> chore(AttributeFormControlUrl):  域名填充规则修改

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(): 实例详情页关系详情跳转入口由基本信息的第一个调整为第一个分类的第一个 closed INSTANCE-2030

- libs/cmdb-instances/src/struct-components/StructTable.tsx
Refs#INSTANCE-2024
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 编辑结构体/结构体数组，不填布尔类型时，应回填空字符串

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
Refs#INSTANCE-2033
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): change the seperator of the content in instance-list-table

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
seperator
Refs#INSTANCE-2033
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add a property to instance-list-table that can change the

- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Refs INSTANCE-2037
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instance-detail): 修复cmdb url类型跳转老数据不生效的问题

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
Refs INSTANCE-2037
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instance-detail): 修复cmdb table url类型跳转老数据不生效的问题

- libs/cmdb-instances/src/cmdb-url-link/CmdbUrlLink.tsx
Refs PRD_OPS-1010
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-url-link): 兼容其他数据格式

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
> fix(cmdb): enum readonly disabled

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs INSTANCE-2055
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 针对默认显示字段的隐藏逻辑去除

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs: NEXT_BUILDER-1176
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support senior search

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
> feat(cmdb-instances): add property onFetchedInstances

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
Refs: INSTANCE-2072
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instance): fix handleSearch when autoSearch was undefined

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-instances/src/struct-components/StructTable.spec.tsx
> fix(cmdb): 结构体支持readonly设置

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> feat(cmdb): 增加属性说明tooltip

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
1、填写不符合规范时，自动定位到首个填写错误项
2、保存按钮不置灰
refs INSTANCE-2086
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): add scrollToFirstError、 offsetTop properties

- libs/cmdb-instances/src/struct-components/AddStruct.tsx
> fix(cmdb): fix新建实例结构体不能编辑bug

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
> feat(cmdb): 数组支持等于/不等于

- libs/cmdb-tree/src/style.module.css
> fix(cmdb): cmdbTree 未选中节点颜色不能为白色

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs INSTANCE-2088
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): cmdb第二次查询, 布尔值转化为字符串导致查询错误

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/pipeline/src/general-pipeline/AddStepButton.module.css
- libs/pipeline/src/general-pipeline/AddStepButton.tsx
> feat(pipeline): AddStepButton支持tooltip

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(cmdb):当对端实例只能关联一个当前模型实例时，列表请求加上{$size:{$lt:1}}

- libs/pipeline/src/general-pipeline/StepItem.module.css
- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.tsx
> feat(pipeline): 支持设置stage文字颜色 && 更改stepitem设置按钮位置

- libs/pipeline/src/general-pipeline/index.module.css
- libs/pipeline/src/general-pipeline/index.tsx
> chore(pipeline): 样式修改

- libs/cmdb-instances/src/instance-detail/index.module.css
Refs BRICK_STORE-2399
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): use css variables

- libs/pipeline/src/general-pipeline/AddStepButton.module.css
- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.module.css
- libs/pipeline/src/general-pipeline/index.spec.tsx
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.spec.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> feat(pipeline): general-pipeline支持serialLine

- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
Refs BRICK_STORE-2391
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): style refine

- libs/forms/src/components/icon-select/IconSelect.module.css
> fix(): support dark theme for IconSelect

- libs/pipeline/src/general-pipeline/constants.ts
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.spec.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> refactor(general-pipeline): Refactor the way of calculation

- libs/forms/src/components/icon-select/IconSelect.module.css
> fix(): fix icon color of IconSelect

- libs/pipeline/src/general-pipeline/AddStepButton.spec.tsx
- libs/pipeline/src/general-pipeline/AddStepButton.tsx
- libs/pipeline/src/general-pipeline/Graphics.spec.tsx
- libs/pipeline/src/general-pipeline/Graphics.tsx
- libs/pipeline/src/general-pipeline/index.spec.tsx
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.spec.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> chore(general-pipeline): extract component && throw more path data

- libs/code-editor-components/src/code-editor/CodeEditor.module.css
Refs BRICK_STORE-2379
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): style modify

- libs/basic-components/src/ZoomPanel/ZoomPanel.module.css
- libs/basic-components/src/ZoomPanel/ZoomPanel.tsx
> fix(): support dark theme for ZoomPanel

- libs/cmdb-instances/src/processors.ts
> chore(cmdb): remove cmdb-advance-search-with-quote featureflag

- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.tsx
> fix(general-pipeline): 修复节点index异常顺序的问题

- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.spec.tsx
> fix(general-pipeline): 节点排序使用自然排序

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
Refs QUALITY-410
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 实例弹窗没有选中实例时禁用确定按钮

- __jest__/setup.ts
- libs/pipeline/src/general-pipeline/AddStepButton.tsx
- libs/pipeline/src/general-pipeline/Graphics.spec.tsx
- libs/pipeline/src/general-pipeline/Graphics.tsx
- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/constants.ts
- libs/pipeline/src/general-pipeline/index.spec.tsx
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.spec.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> chore(general-pipeline): refRepository remember nodeData

- libs/pipeline/src/general-pipeline/Graphics.spec.tsx
- libs/pipeline/src/general-pipeline/Graphics.tsx
- libs/pipeline/src/general-pipeline/constants.ts
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> fix(general-pipeline): pathlength 为空时不显示箭头

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(cmdb): 请求实例时fields过滤掉已删除的属性

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
如果父模型中没定义但子模型中定义了，也是可以获取到的
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 不过滤模型中不存在的字段

- libs/cmdb-instances/src/instance-list-table/DisplaySettings.tsx
- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.tsx
- libs/cmdb-instances/src/instance-list-table/index.ts
> feat(DisplaySettings): add extraDisabledFields property

- libs/pipeline/src/general-pipeline/StepItem.spec.tsx
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.tsx
- libs/pipeline/src/general-pipeline/util.tsx
> feat(general-pipeline): add operateButtonsTrigger property

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
refs NEXT_BUILDER-1257
请勾选以下两组选项其中之一：
或者：
>
>
> modify style

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
Refs#MONITOR-2935
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 使InstanceListModal可以隐藏实例列表的搜索条件

- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.spec.tsx
- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.tsx
> fix(DisplaySettingsModal): reset fields when modal close

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(cmdb): 新建实例可配置确定按钮的文案

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
> fix(cmdb): cmdb-instances.cmdb-instances-input-form添加按钮可禁用

- libs/pipeline/src/general-pipeline/AddStepButton.module.css
- libs/pipeline/src/general-pipeline/Graphics.tsx
- libs/pipeline/src/general-pipeline/StepItem.module.css
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.module.css
- libs/pipeline/src/general-pipeline/index.tsx
Refs#BRICK_STORE-2591
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): adapt to the dark theme

- libs/pipeline/src/general-pipeline/Graphics.tsx
- libs/pipeline/src/general-pipeline/StepItem.module.css
- libs/pipeline/src/general-pipeline/StepItem.tsx
- libs/pipeline/src/general-pipeline/index.module.css
> chore(): replace css variables

- libs/basic-components/src/Link.spec.tsx
- libs/basic-components/src/Link.tsx
> feat(link): support setting noEmptyHref

- libs/forms/src/FormItemWrapper.module.css
Refs BRICK_STORE-2626
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): typo

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs INSTANCE-2271
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 添加关系实例时要拉对端模型关联的所有模型

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
> fix(): 修复validateJsonSchemaMode为error时不生效

- libs/forms/src/FormItemElement.spec.ts
- libs/forms/src/FormItemElement.ts
> refactor(FormItemElement): set hidden property in notRender setter

- libs/permission-utils/package.json
- libs/permission-utils/src/components/CommonSetting.spec.tsx
- libs/permission-utils/src/components/CommonSetting.tsx
- libs/permission-utils/src/components/SelectUserOrGroup.tsx
- yarn.lock
> feat(): CommonSetting构件选择用户组时传递的应该是实例id refs APP_PERMIT-163

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs#INSTANCE-2253
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 添加实例范围，条件过滤删除其中一个条件过滤，另外一个条件过滤也会被删除

- libs/permission-utils/src/components/BatchHandleUser.spec.tsx
- libs/permission-utils/src/components/BatchHandleUser.tsx
- libs/permission-utils/src/components/BatchSetting.spec.tsx
- libs/permission-utils/src/components/BatchSetting.tsx
- libs/permission-utils/src/components/CommonSetting.spec.tsx
- libs/permission-utils/src/components/CommonSetting.tsx
- libs/permission-utils/src/components/SelectUserOrGroup.tsx
- libs/permission-utils/src/interfaces.ts
Refs CD-2520
请勾选以下两组选项其中之一：
或者：
>
>
> feat(SelectUserOrGroup): support backend search

- libs/forms/src/FormItemWrapper.module.css
Refs: BRICK_STORE-2678
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-forms): 适配通用表单说明文字的暗色

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs#INSTANCE-2331
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复高级搜索筛选条件不能清除

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
refs DEVOPS_MANAGEMENT-370
请勾选以下两组选项其中之一：
或者：
>
>
> fix(CmdbInstancesSelectPanel): fix value改变后，panel表格数据不更新

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
This reverts commit 79dbd3f41ae2ace79c5114d7a3bdd860187fa67e.
请勾选以下两组选项其中之一：
或者：
>
>
> Revert "fix(CmdbInstancesSelectPanel): fix value改变后，panel表格数据不更新"

- libs/forms/src/components/icon-select/IconSelect.tsx
Refs BRICK_STORE-2323
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix icon backfill value

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
close TRANSFER-97
请勾选以下两组选项其中之一：
或者：
>
>
> fix(CmdbInstancesSelectPanel): props.value bug fix

- libs/basic-components/src/Link.spec.tsx
- libs/basic-components/src/Link.tsx
> feat(): support disabled link

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
> chore(CmdbInstancesSelectPanel): clear props.value loops

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Refs#DATA_QUALITY-212
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复分类排序失效

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(cmdb): 显示字段取默认前8个时忽略禁止显示的字段

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> feat(): instance-list-modal支持IP类型的字段可以copy功能 Refs MONITOR-3543

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
> fix(codeEditor): fix re-render complete  error

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> feat(): instance modal 支持自定义分页以及显示关闭按钮 Refs MONITOR-3543

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): ipCopy功能过滤 Refs MONITOR-3544

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs#INSTANCE-2395
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改cmdb实例创建保存不会回滚到第一个校验报错点

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix修复ipCopy复制功能点击文字的清空，还能复制的问题 Refs MONITOR-3550

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
> chore(CmdbInstancesSelectPanel): sort props.value

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.spec.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
of Select to value
Closes TOOL-1114
请勾选以下两组选项其中之一：
或者：
>
>
> fix(ModelAttributeFormControl): change defaultValue property

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(InstanceModelAttributeForm): 修改任意字符会重新拉所有的请求 Closes INSTANCE-2410

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 修复回显时候ipCopy功能获取不到数据的问题  Refs BRICK_STORE-276

- .size-limit.js
- libs/cmdb-instances/src/index.ts
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.module.css
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.tsx
- libs/cmdb-instances/src/instance-list-table/index.ts
Refs#MONITOR-3554
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): finish AdvancedSearchCondition component

- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.tsx
- libs/cmdb-instances/src/instance-list-table/DynamicSearch.module.css
- libs/cmdb-instances/src/instance-list-table/DynamicSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/DynamicSearch.tsx
refs# MONITOR-3554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 新增动态筛选的构件

- libs/cmdb-instances/src/instance-list-table/DynamicSearch.tsx
refs#MONITOR-3561
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): change show components

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 暴露点击事件的行数据 refs PERMISSION-217

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Refs#CMDB-SERVICE-562
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 通过获取指定字段优化实例详情接口

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(cmdb): 固定表头后横向拥挤错位

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
Refs TRANSFER-99
请勾选以下两组选项其中之一：
或者：
>
>
> feat(CmdbInstancesInputFormItem): add pageSizeOptions property

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 增加当presetConfigs属性变动的时候, 重新刷新列表 refs PERMISSION-239

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(cmdb): 拉取实例详情时忘了await

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/cmdb-utils/src/cmdbUtil.spec.ts
- libs/cmdb-utils/src/cmdbUtil.ts
> fixed(InstanceModelAttributeForm): 固定表单保存操作 Closes INSTANCE-2430

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> feat(): InstanceListModal添加rowSelectTye属性 refs TOOL-1121

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 去掉props.presetConfigs变更刷新页面 refs PERMISSION-239

- libs/forms/src/FormItemElement.ts
> chore(): add doc comment

- libs/basic-components/src/Link.spec.tsx
- libs/basic-components/src/Link.tsx
> chore(Link): refine disabled style

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
close CD-2687
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): addAllowClear

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 修复具体实例中为空不为空和区间的删除及回显问题 Closes INSTANCE-2422

- libs/cmdb-instances/src/i18n/constants.ts
- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
> fix():实例详情的基本信息页面的实例关系表格展示也能支持分页 Closes INSTANCE-2459

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix():修改实例表格详情弹框的宽度 Closes INSTANCE-2459

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> refactor(): 删除不必要代码 refs DEVOPS_MANAGEMENT-469

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-2516
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 高级搜索选择在此区间时，只填入一半条件搜索时没正常显示筛选条件

- libs/datetime-components/src/datetime-range/DatetimeRange.spec.tsx
- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
refs: SERVICE_OBSERVE-1575
请勾选以下两组选项其中之一：
或者：
>
>
> feat(datetime-range): 指定范围时间选择器增加限制选择近n天属性

- libs/forms/src/FormItemElement.ts
> docs(): doc refine

- libs/forms/src/FormItemElement.ts
Refs BRICK_STORE-2992
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): tirm property default value set true

- .size-limit.js
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- package.json
- yarn.lock
Refs MONITOR-3748
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instance): 实例列表支持调用search-resource接口

- libs/cmdb-tree/src/CMDBTree.tsx
- libs/cmdb-tree/src/processors.spec.ts
- libs/cmdb-tree/src/processors.ts
> feat(): cmdb实例关系树构件支持按白名单过滤节点 refs ORCHESTRATION-168

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-2587
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 动态过滤选择在此期间报错

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs INSTANCE-2555
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 实例列表的presetConfigs添加一个额外固定列的选项

- libs/cmdb-tree/src/CMDBTree.tsx
> fix(): cmdb实例关系树构件过滤白名单异常 refs ORCHESTRATION-168

- libs/cmdb-instances/src/instance-detail/index.module.css
ref INSTANCE-2592
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 实例详情多行字符串支持换行显示

- libs/code-editor-components/src/code-editor/CodeEditor.module.css
- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/i18n/constants.ts
- libs/code-editor-components/src/i18n/locales/en.ts
- libs/code-editor-components/src/i18n/locales/zh.ts
- libs/code-editor-components/src/interfaces.ts
- libs/code-editor-components/src/share.module.css
> feat(): support expand editor

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
> fix(): allow users to press esc and exit expanded mode

- libs/code-editor-components/src/share.module.css
> fix(): fix scrollbar overlaid on toolbar

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
ref: INSTANCE-2671
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 编辑与创建模型对象实例时，点击保存准确定位到底部校验错误字段位置

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
ref: CMDB-SERVICE-581
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 实例编辑时,关系数据添加面板中的列表需要支持showSizeChanger实现页面条数选择

- libs/cmdb-tree/src/CMDBTree.tsx
ref: DEVOPS_MANAGEMENT-579
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-tree): 增加无从属系统的应用节点并且展开获取数据以及展开所有时增加该节点

- libs/cmdb-tree/src/CMDBTree.tsx
ref: INSTANCE-2684
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-tree): 通过指定模型优化object_all接口请求速度

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 修复extraFixedFields在显示设置后不生效问题 refs PERMISSION-291

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> feat(): 支持小产品定制Ip搜索or字段条件  refs INSTANCE-2703

- libs/cmdb-instances/package.json
- libs/cmdb-instances/src/__mocks__/fetchCmdbInstanceSearch.ts
- libs/cmdb-instances/src/__mocks__/index.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceDetail.spec.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceDetail.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceSearch.spec.ts
- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceSearch.ts
- libs/cmdb-instances/src/data-providers/index.ts
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
- yarn.lock
Refs:INSTANCE-2709
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 优化实例关系数据量大的问题

- libs/cmdb-instances/src/index.ts
> fix(): fix type warnings

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Closes INSTANCE-2756
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instanceDetail): tag是undefined报错

- libs/basic-components/src/GeneralIcon.tsx
> fix(): prepend public root for img src if applicable

- libs/hooks/package.json
- libs/hooks/src/index.ts
- libs/hooks/src/useUserInfoByNameOrInstanceId.spec.tsx
- libs/hooks/src/useUserInfoByNameOrInstanceId.ts
> feat(): support useUserInfoByNameOrInstanceId

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs:INSTANCE-2781
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复结构体数据搜索,删除选项删除不掉的问题

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs:INSTANCE-2781
请勾选以下两组选项其中之一：
或者：
>
>
> fix():调整结构体数据搜索,删除选项删除不掉

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> chore(): 逻辑调整

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/cmdb-tree/src/style.module.css
> fix(): cmdb-tree选中状态的子节点背景色调整  refs CD-3084

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): ModelAttributeForm调整按钮位置  refs CD-3084

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs INSTANCE-2836
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 实例列表使用provider接口时，请求参数中的fields加关系对端模型的showkey

- libs/visual-builder/src/index.ts
- libs/visual-builder/src/interfaces/index.ts
- libs/visual-builder/src/interfaces/workbench-mini-action-bar.ts
- libs/visual-builder/src/utils/deepMatch.spec.ts
- libs/visual-builder/src/utils/deepMatch.ts
- libs/visual-builder/src/utils/index.ts
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.module.css
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.spec.tsx
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx
> feat(): migrate shared component to libs

- libs/basic-components/src/Link.spec.tsx
- libs/basic-components/src/Link.tsx
- libs/basic-components/src/getExtendedLocationDescriptor.spec.ts
- libs/basic-components/src/getExtendedLocationDescriptor.ts
> feat(Link): support keepCurrentSearch

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix(): InstanceList补充extraFixedFields属性 refs TOOL-1197

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Ref: CD-3071
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复cmdb实例窗口切换过滤方式没有重置页码的问题

- libs/visual-builder/src/interfaces/brick-visualization.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.spec.tsx
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/CodeEditor/CodeEditorFormItem.tsx
- libs/visual-builder/src/visual-property-form/constant.ts
- libs/visual-builder/src/visual-property-form/processor.spec.ts
- libs/visual-builder/src/visual-property-form/processor.ts
Refs FLOW_BUILDER-418
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support hiddenPropsCategory

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> feat(): intanceList propertyDisplayConfigs support useBrick

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
Refs FLOW_BUILDER-432
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix local variables suggestions not work

- libs/basic-components/EmptyResult.js
- libs/basic-components/EmptyResultStatus.js
- libs/basic-components/package.json
- libs/basic-components/src/EmptyResult.spec.tsx
- libs/basic-components/src/EmptyResult.tsx
- libs/basic-components/src/EmptyResultStatus.ts
- libs/basic-components/src/index.ts
for better tree-shaking for assets
BREAKING CHANGE: `EmptyResult` and `EmptyResultStatus` are exported separately now
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): export `EmptyResult` and `EmptyResultStatus` separately

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> feat(): instanceList support presetConfigs.query refresh

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageRules.ts
> fix(): add snippets

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
> feat(CodeEditor): support update jsonSchema property

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/interfaces.ts
> feat(): support showGutter

- .size-limit.js
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): 模型视图里关系删除后不在实例详情和编辑里出现 Closes INSTANCE-2991

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
Reverts easyops-cn/next-libs#443
> Revert "feat(CodeEditor): support update jsonSchema property"

- declarations/global.d.ts
- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
> fix(general-icon): support noPublicRoot

- libs/forms/src/FormItemWrapper.tsx
> fix(FormItemWrapper): fix no ref input not force rerender correctly

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(cmdb): 实例详情锚点往上挪一点

- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
Closes INFRA-001
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support withFormItemWrapper HOC

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/code-editor/getHighlightMarkers.spec.ts
- libs/code-editor-components/src/code-editor/getHighlightMarkers.ts
- libs/code-editor-components/src/interfaces.ts
such as context-action, state-action and tag-name-as-target
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support more error markers

- libs/code-editor-components/src/code-editor/getHighlightMarkers.spec.ts
- libs/code-editor-components/src/code-editor/getHighlightMarkers.ts
> fix(): allow target: _self

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
ref: INSTANCE-3104
请勾选以下两组选项其中之一：
或者：
>
>
> feat(instance-list): 通过useInstanceArchiveProvider参数使得构件列表数据支持使用归档接口

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- package.json
- yarn.lock
ref: INSTANCE-3104
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 实例列表归档接口不缓存

- libs/cmdb-instances/src/struct-components/StructTable.tsx
Closes MONITOR-4239
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 实例预览popover内modal层级错误

- libs/basic-components/jest.config.js
- libs/charts/jest.config.js
- libs/clipboard/jest.config.js
- libs/cmdb-instances/jest.config.js
- libs/cmdb-tree/jest.config.js
- libs/cmdb-utils/jest.config.js
- libs/code-display-components/jest.config.js
- libs/code-editor-components/jest.config.js
- libs/constants/jest.config.js
- libs/crontab/jest.config.js
- libs/datetime-components/jest.config.js
- libs/datetime/jest.config.js
- libs/forms/jest.config.js
- libs/hooks/jest.config.js
- libs/permission-utils/jest.config.js
- libs/pipeline/jest.config.js
- libs/searchable-tree/jest.config.js
- libs/storage/jest.config.js
- libs/storyboard-visualization/jest.config.js
- libs/svga/jest.config.js
- libs/user-components/jest.config.js
- libs/visit-history/jest.config.js
- libs/visual-builder/jest.config.js
- package.json
> chore(): refine test scripts

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs INSTANCE-3141
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 新建编辑实例时，防止保存按钮可重复多次点击

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): optimize mult object_ref interfaces call

- libs/basic-components/src/Link.spec.tsx
- libs/basic-components/src/Link.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> feat(): breaking change 使用原生点击事件实现Link行为 Refs:EASY_AGILE-873

- libs/forms/src/FormItemElement.ts
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
> feat():formItemWrapper新增属性：labelBold，LabelColor，refs:FORM_BUILDER-155

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> chore(): fix object ref not find

- libs/basic-components/src/Link.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> feat(): fix link: specify useNativeEvent explicitly

- libs/user-components/src/mentions/Mentions.spec.tsx
- libs/user-components/src/mentions/Mentions.tsx
> fix(CommentBrick): 查询结果默认显示showkey  Refs: ITSERVICE_NEXT-5114

- libs/basic-components/src/GeneralIcon.tsx
> feat(): support lazy image loading

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): ModelAttributeForm接口报错后恢复按钮 Closes INSTANCE-3240

- libs/code-editor-components/src/code-editor/getHighlightMarkers.spec.ts
- libs/code-editor-components/src/code-editor/getHighlightMarkers.ts
- libs/code-editor-components/src/interfaces.ts
> fix(): warn route var such as PATH in tpl

- libs/code-editor-components/src/custom-mode/CommonExpressionLanguageRules.ts
Refs FLOW_BUILDER-568
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cel mode add completer

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/ListEditor/ListEditor.module.css
- libs/visual-builder/src/visual-property-form/components/ListEditor/ListEditor.tsx
> feat(): update visual-property-form

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.spec.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
refs:DESKTOP-299
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 预防和修复实例编辑构件分类排序的问题

- .size-limit.js
- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.spec.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-instances/src/struct-components/StructTable.spec.tsx
- libs/cmdb-instances/src/struct-components/StructTable.tsx
> fix():关系详情结构体表格和关系表格增加搜索  Closes INSTANCE-3323

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix():关系表格搜索清空不了  Closes INSTANCE-3323

- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-utils/src/processors/object.ts
> fix():搜索后编辑和删除数据不对 Closes INSTANCE-3323

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
closeCD-3575
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 新建应用实例时，点击保存并继续添加后 表格内容清空

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
> fix(): 修复字段name和表单属性冲突的问题

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
> fix(): 修复实例编辑展示code-editor,出现死循环的问题

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
ref: CMDB_EXTEND-233
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): objectList为空数组时,if判断为真,造成ref接口无法调用

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
> fix():搜索框距离表格的边距不对 Closes INSTANCE-3323

- libs/visual-builder/src/interfaces/brick-visualization.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/ListEditor/ListEditor.module.css
- libs/visual-builder/src/visual-property-form/components/ListEditor/ListEditor.tsx
> feat(): update visual property form style

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs:INSTANCE-3359
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复实例列表查询没有回显成功

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Closes INSTANCE-3403
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复模型属性表单如果有`nodename`属性就报错bug

- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.tsx
refs MONITOR-4599
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): add hideDynamicSearch prop

- libs/forms/src/components/icon-select/IconSelect.spec.tsx
- libs/forms/src/components/icon-select/IconSelect.tsx
Refs BRICK_STORE-3222
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick_store): 修复图标选择构件图标搜索bug

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/ListEditor/ListEditor.tsx
- libs/visual-builder/src/visual-property-form/components/MenuEditor/MenuEditorItem.tsx
- libs/visual-builder/src/visual-property-form/processor.spec.ts
- libs/visual-builder/src/visual-property-form/processor.ts
> feat(): support both change

- libs/hooks/src/useUserInfoByNameOrInstanceId/useUserInfoByNameOrInstanceId.ts
close
NEXT_BUILDER-2513
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改getUserInfoByNameOrInstanceId请求

- libs/cmdb-tree/src/CMDBTree.tsx
refs CD-3791
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): CD-3791 【持续交付】部署编排业务树获取接口没有校验基础权限点【应用系统访问】，导致返回的数据里存在用户无法查看的实例

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
Closes MONITOR-4119
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 查看实例modal应该只有关闭按钮

- libs/hooks/src/useUserInfoByNameOrInstanceId/useUserInfoByNameOrInstanceId.ts
Closes BRICK_STORE-3285
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): userAvatar 返回用户信息时增加了showKey

- libs/cmdb-instances/src/instance-list/InstanceList.module.css
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs:INSTANCE-3839
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add loading in instances-list

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
refs CD-3926
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): CmdbInstancesselectPanel 暴露属性aq

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs CD-3230
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 导出translateConditions方法

- libs/visual-builder/src/interfaces/brick-visualization.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/CodeEditor/CodeEditorFormItem.tsx
- libs/visual-builder/src/visual-property-form/processor.spec.ts
- libs/visual-builder/src/visual-property-form/processor.ts
refs NEXT_BUILDER-2667
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 优化样式,修复一些小问题

- libs/forms/src/FormItemElement.ts
> fix(): 修复文档没有生成继承属性的问题

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
> chroe(cmdb-instances): support advancedSearchDisabled

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
refs TRANSFER-134
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): CmdbInstancesInputFormItem补充page_size属性

- libs/visual-builder/src/interfaces/brick-visualization.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/ColorEditor/ColorEditor.module.css
- libs/visual-builder/src/visual-property-form/components/ColorEditor/ColorEditorItem.tsx
- libs/visual-builder/src/visual-property-form/components/MessageEditor/MessageEditor.module.css
- libs/visual-builder/src/visual-property-form/components/MessageEditor/MessageEditor.tsx
> feat(): support message editor

- libs/forms/src/FormItemElement.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.spec.tsx
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/constant.ts
- libs/visual-builder/src/visual-property-form/processor.spec.ts
refs NEXT_BUILDER-2693
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 优化radio样式,新增几种内置分类

- libs/forms/src/FormItemElement.ts
- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
- libs/forms/src/interfaces.ts
refs NEXT_BUILDER-2693
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 增加labelAlign属性, 优化属性editor

- libs/basic-components/src/utils/getIconList.spec.ts
- libs/basic-components/src/utils/getIconList.ts
> fix(): getIconList增加过滤category条件

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
Ref: NEXT_BUILDER-2695
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix VB editor bug

- libs/forms/src/FormItemElement.ts
> docs(): update form docs

- package.json
- yarn.lock
> chore(): update next-core/brick-icons version

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.module.css
- libs/visual-builder/src/visual-property-form/processor.ts
> feat(): update visual-property-form process

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/cmdb-instances/src/processors.spec.ts
- libs/cmdb-instances/src/processors.ts
Closes INSTANCE-4562
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复集群类型以中文显示

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
> fix(): INSTANCE-4576 新建实例时，保存并继续添加，之前填写的值清空了 refs INSTANCE-4576

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.spec.tsx
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
> feat(): feat textarea and number editor

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.spec.tsx
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
> feat(): feat radio editor disableUncheck

- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
- libs/visual-builder/src/visual-property-form/components/ColorEditor/ColorEditorItem.spec.tsx
- libs/visual-builder/src/visual-property-form/components/ColorEditor/ColorEditorItem.tsx
> feat(): feat color editor preset color

- libs/hooks/src/avatar/useAvatar.tsx
- libs/hooks/src/index.ts
> chore(useAvatar): support getAvatar

- libs/pipeline/src/general-pipeline/index.module.css
refs:MONITOR-5797
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): change style

- libs/code-editor-components/src/code-editor/CodeEditor.spec.tsx
- libs/code-editor-components/src/code-editor/CodeEditor.tsx
- libs/code-editor-components/src/interfaces.ts
> feat(): codeEditor的模式为yaml时，支持以字符串---分割成多个文件  refs WORKSPACE-174

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): 去掉搜索后默认清空 Closes COLLECTOR_CENTER-404

- libs/code-editor-components/src/custom-mode/BrickNextRules.ts
> feat(): support brick next new syntax

- libs/forms/src/components/icon-select/IconSelect.tsx
close DESIGNER_ROUTINE-628
请勾选以下两组选项其中之一：
或者：
>
>
> fix(icon-select): 选择图标构件的搜索框应与单选框居中对齐

- libs/hooks/src/mention/useMention.spec.tsx
- libs/hooks/src/mention/useMention.tsx
> fix(mention):支持 输入@的时候搜索前几条数据 Refs ITSERVICE_NEXT-6222

- libs/crontab/src/regex.ts
close
CRONTAB-495
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 周期构件校验支持L字符

- libs/basic-components/src/GeneralIcon.tsx
- libs/basic-components/src/Sidebar.tsx
- libs/basic-components/src/__snapshots__/Sidebar.spec.tsx.snap
> chore(): sidebar icon set size

- libs/crontab/src/regex.ts
> fix(): crontab支持L字符

- libs/visual-builder/src/interfaces/workbench-mini-action-bar.ts
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx
Refs NEXT_BUILDER-3189
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support iconUseBrick

- .size-limit.js
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
refs INSTANCE-4931
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 数据类型为int/float时，输入非数字展示有问题

- libs/datetime-components/src/datetime-range/DatetimeRange.spec.tsx
- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
> feat(datetime): 增加rangeDays属性控制选择范围天数

- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
> fix(datetime): 修改rangeDays属性bug

- libs/datetime-components/src/datetime-range/DatetimeRange.spec.tsx
- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
> fix(datetime): fix rangeDays bug

- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
- libs/forms/src/FormItemWrapper.tsx
Refs INSTANCE-4765
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb): 实例详情展示关系默认视图中指定的字段

- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
Refs INSTANCE-4992
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 指定关系默认字段的在实例详情中要根据attr_order排一下序

- libs/forms/src/interfaces.ts
- libs/visual-builder/src/visual-property-form/VisualPropertyForm.tsx
Refs NEXT_BUILDER-3218
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update GeneralOptions form

- .size-limit.js
- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
关系的showKey样式不省略
Refs INSTANCE-5042
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 实例详情显示关系的关系时应当与拉对端模型关联的模型

- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.tsx
> fix(): 修复extraDisabledField字段未生效  Refs API_GW-145

- libs/cmdb-utils/src/parseTemplate.spec.ts
- libs/cmdb-utils/src/parseTemplate.ts
Ref: BRICK-7
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cmdb-select构件的labelTemplate支持关系字段

- libs/code-editor-components/src/custom-mode/brickNextUtil.ts
> fix(): add brickNextKeywords

- libs/cmdb-instances/src/i18n/constants.ts
- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix(cmdb): 实例选择弹窗左侧下方添加一个新建并绑定按钮

- libs/cmdb-instances/src/i18n/constants.ts
- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix(cmdb): cmdb实例弹窗新建并绑定按钮disabled属性

- libs/basic-components/src/GeneralIcon.tsx
> fix(): fix fa-icon vertical align in v3

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.module.css
Closes DESIGNER_ROUTINE-665
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 按钮圆角调整

- libs/basic-components/src/GeneralIcon.tsx
refs CMDB_INSTANCE-154
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 增加icon类样式,使其可以支持hover效果

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs weili-test-001
请勾选以下两组选项其中之一：
或者：
>
>
> feat(instance-list): 新增强制刷新实例列表参数

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_CONSUME-18
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cmdb-instance-list构件支持动态设置query

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
Refs CMDB_INSTANCE-448
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 实例新建/编辑可对枚举值进行搜索

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list/FilterInstanceSource.tsx
refs: CMDB_INSTANCE-345
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复实例弹窗构件开启实例来源过滤的问题

- libs/cmdb-instances/src/instance-list/FilterInstanceSource.tsx
refs: CMDB_INSTANCE-345
请勾选以下两组选项其中之一：
或者：
>
>
> fix():实例列表的实例来源根据instanceId过滤

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> test(): update test case

- libs/cmdb-instances/src/instance-list-table/utils.spec.ts
- libs/cmdb-instances/src/instance-list-table/utils.ts
Closes INSTANCE-4420
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 主机的磁盘大小和内存大小要改成1000+GB的换算

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
refs MONITOR_SETTING-72
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 指定实例当数量超过5条时，点击查看实例，未透传fields，导致弹窗内字段显示不一致

- libs/cmdb-instances/src/instance-list/FilterInstanceSource.module.css
- libs/cmdb-instances/src/instance-list/FilterInstanceSource.spec.tsx
- libs/cmdb-instances/src/instance-list/FilterInstanceSource.tsx
refs: CMDB_VIEW-2
请勾选以下两组选项其中之一：
或者：
>
>
> fix():修复实例查询过滤的问题

- libs/basic-components/src/GeneralIcon.spec.tsx
- libs/basic-components/src/GeneralIcon.tsx
Closes NEXT_BUILDER-3492
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 无法显示用户上传的图片

- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.spec.tsx
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx
> fix(WorkbenchMiniActionBar): support prop `useNativeEvent`

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
refs ALERT_EVENT-314
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复cmdb-instances-select-panel中InstanceListModal漏了pageSize 的配置

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs CMDB_INSTANCE-641
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 实例详情和列表支持越权查询

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs CMDB_INSTANCE-639
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 新增显示列的排序不会影响配置列的排序

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
Refs CMDB_INSTANCE-640
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 越权查询时隐藏关系的跳转

- .size-limit.js
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Refs CMDB_INSTANCE-640
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 越权查询时更多关系实例也要用越权接口

- .size-limit.js
- libs/cmdb-instances/src/instance-detail/InstanceDetail.spec.tsx
- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.module.css
- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.spec.tsx
- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.tsx
Closes CMDB_INSTANCE-663
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 列表&详情查看JSON数据时提供格式化的数据预览

- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.tsx
Closes CMDB_INSTANCE-663
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): 修改JSON预览最少行数

- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.tsx
Closes CMDB_INSTANCE-663
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): json预览去掉显示打印边距

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
Refs CMDB_INSTANCE-722
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): fix实例详情构件对端实例字段获取不全问题

- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.spec.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
- libs/cmdb-instances/src/processors.spec.ts
- libs/cmdb-instances/src/processors.ts
Closes CMDB_INSTANCE-700
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb-instances): agent状态筛选条件设置为为空，接口报错

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
Refs CMDB_INSTANCE-653
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): fix实例详情中的关系列表实例来源不显示及无法筛选bug

- libs/crontab/src/format.spec.ts
- libs/crontab/src/format.ts
- libs/crontab/src/i18n/constants.ts
- libs/crontab/src/i18n/locales/en.ts
- libs/crontab/src/i18n/locales/zh.ts
> fix():TOOL-1536 售中工单_定时任务crontab表达式失效 ref TOOL-1536

- libs/crontab/src/format.ts
- libs/crontab/src/i18n/index.ts
> fix():TOOL-1536 国际化问题 ref TOOL-1536

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/components/user-or-user-group-select/UserOrUserGroupSelect.tsx
Refs TOOL-1553
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): CmdbInstancesSelectPanel support saveFieldsBackend

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
refs: CMDB_EXTEND-392
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复自关联模型关系数量显示不对的场景

- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_INSTANCE-874
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instances): 默认显示列，需显示关系字段

- .github/workflows/ci.yml
> chore(): ci on legacy branches

- .github/workflows/ci.yml
> chore(ci): update npm mirror syncing url

- libs/cmdb-instances/src/float-display-brick/FloatDisplayBrick.spec.tsx
- libs/cmdb-instances/src/float-display-brick/FloatDisplayBrick.tsx
Closes CMDB_EXTEND-395
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 浮点型属性值的负数显示的是正数

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.module.css
- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
- libs/cmdb-instances/src/struct-components/AddStruct.tsx
- libs/cmdb-utils/src/cmdbUtil.ts
> fix(): cmdb部分构件 适配UI8.2

- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.tsx
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
- libs/cmdb-utils/src/cmdbUtil.ts
Closes CMDB_INSTANCE-899
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 适配UI8.2

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(instance-detail): anchor compatible with new page view

- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-input-form/CmdbInstancesInputFormItem.tsx
> fix():CmdbInstancesInputFormItem请求优化 ref ARTIFACT-740

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_EXTEND-398
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cmdb-instances.instance-list构件支持获取表头顺序

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
> fix(): 修改实例结构体属性按钮样式

- .size-limit.js
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.spec.tsx
- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-detail/components/instance-relation-table-show/instance-relation-table-show.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> chore(): 支持外部接口调用

- libs/cmdb-utils/src/i18n/locales/zh.ts
> fix(): 资源变更历史，变更类型 列表页与详情页要保持一致

- libs/cmdb-instances/src/instance-detail/index.module.css
- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.module.css
Closes CMDB_CONSUME-124
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 样式污染全局

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> chore(): 优化postsearchv3和v1接口参数调整

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
> fix(): 实例列表固定列出现的样式bug

- libs/forms/src/components/icon-select/IconSelect.tsx
Closes STORE-46
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): use text cancel button in modal

- libs/cmdb-instances/src/instance-list-table/DisplaySettingsModal.tsx
Closes CMDB_INSTANCE-1048
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 未选中字段时默认显示按钮置灰

- libs/cmdb-instances/src/json-display-brick/JsonDisplayBrick.tsx
> chore(): 修复value为undefined的没有length属性报错

- libs/cmdb-tree/src/processors.spec.ts
- libs/cmdb-tree/src/processors.ts
> fix():问题修复 ref ORCHESTRATION-327

- libs/code-editor-components/src/code-editor/CodeEditor.module.css
> fix(): 编辑框宽度变化后存在样式问题

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> chore(): 支持隐藏显示和隐藏省略号图标

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/index.module.css
refs CMDB_VIEW-115
请勾选以下两组选项其中之一：
或者：
>
>
> feat(instance-detail): useHttpErrorString支持展示报错插画

- libs/basic-components/src/GeneralIcon.tsx
Closes CD-7371
请勾选以下两组选项其中之一：
或者：
>
>
> feat(GeneralIcon): add onMouseEnter and onMouseLeave properties

- libs/cmdb-tree/src/CMDBTree.tsx
> fix():修复cmdbTree构件开启权限校验时未使用APP模型的报错问题 ref ORCHESTRATION-327

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.spec.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Refs NWYD-1618
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instanceListTable): 实例列表增加序号列开关

- libs/cmdb-instances/package.json
Closes CMDB_MODEL-63
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): update @next-libs/code-display-components

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
Closes CMDB_MODEL-63
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): code-editor 默认值

- libs/cmdb-instances/src/struct-components/AddStructModal.tsx
Closes CMDB_MODEL-69
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 结构体modal打开没有更新form value

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
Closes CMDB_CONSUME-310
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): CMDB的单选枚举值，非必填，没选之前可以是空的，但是选了之后就不能为空

- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
Closes APM-1014
请勾选以下两组选项其中之一：
或者：
>
>
> fix(datetime-selector):  修复props更新没有更新对应state状态导致构件效果不对

- libs/cmdb-utils/src/parseTemplate.spec.ts
- libs/cmdb-utils/src/parseTemplate.ts
Refs APM-1011
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): parseTemplate支持解析#showKey

- libs/visual-builder/src/interfaces/workbench-mini-action-bar.ts
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.spec.tsx
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx
> fix(): pass position data

- libs/datetime-components/src/datetime-range/DatetimeRange.spec.tsx
- libs/datetime-components/src/datetime-range/DatetimeRange.tsx
Closes CI-163
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 筛选时间会多传一点ms

- libs/visual-builder/src/interfaces/workbench-mini-action-bar.ts
- libs/visual-builder/src/workbench-mini-action-bar/WorkbenchMiniActionBar.tsx
> feat(): support tooltip

- libs/code-editor-components/src/code-editor/CodeEditor.tsx
Refs CD-8090
请勾选以下两组选项其中之一：
或者：
>
>
> feat(CodeEditor): add disable_lint_yaml mode

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> chore(): 实例列表模态框支持propertyDisplayConfigs配置

- libs/cmdb-utils/src/cmdbUtil.spec.ts
- libs/cmdb-utils/src/cmdbUtil.ts
Closes CMDB_INSTANCE-1725
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 层级枚举值解析有点问题， 例如把【a/b/c1】,当成了【a/b/c111】子节点了

- libs/cmdb-utils/src/cmdbUtil.ts
Closes CMDB_INSTANCE-1725
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): node没有children时报错

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
refs: CMDB_INSTANCE-1718
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 实例编辑构件支持可配置上传参数

- libs/cmdb-instances/src/components/cmdb-upload/index.tsx
refs: CMDB_INSTANCE-1718
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复文案显示问题

- libs/cmdb-utils/src/processors/formatAttrValue.ts
refs: CMDB_INSTANCE-1664
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 支持属性附件类型值处理

- libs/cmdb-instances/src/instance-detail/components/instances-attachment-display/instances-attachment-display.tsx
refs: CMDB_INSTANCE-1664
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 调整预览地址,添加checksum和fullfilename参数

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-list-table/AdvancedSearch.tsx
- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
- libs/cmdb-utils/src/processors/formatAttrValue.ts
refs: CMDB_MODEL-73
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 调整附件属性的方案

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
modalWidth
Closes CMDB_INSTANCE-874
请勾选以下两组选项其中之一：
或者：
>
>
- [] 给新特性添加了单元测试。
> feat(cmdb-instances): InstanceListModal support

- libs/cmdb-instances/src/components/cmdb-upload/index.spec.tsx
- libs/cmdb-instances/src/components/cmdb-upload/index.tsx
refs: CMDB_INSTANCE-1754
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 上传支持自定义配置

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
refs: ZYHLWCMDB-85
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 支持父模型情况下,隐藏实例来源的这一列

- libs/cmdb-instances/src/index.ts
> fix(): FLOW-1282 export cmdb-instances下面的componnents下面的子组件 ref FLOW-1282

- .size-limit.js
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_INSTANCE-1747
Closes CMDB_INSTANCE-874
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 售中工单_模型实例列表页面，当前筛选条件字段为多选枚举型时，无法删除筛选条件

- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceDetail.ts
Refs CMDB_CONSUME-436
请勾选以下两组选项其中之一：
或者：
>
>
> style(cmdb-detail): 修复实例详情代理接口响应体问题

- libs/forms/src/FormItemWrapper.spec.tsx
- libs/forms/src/FormItemWrapper.tsx
Closes SHLSTYYWPT-740
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): FormItemWrapper 的 labelTooltip 支持换行

- libs/cmdb-instances/src/model-attribute-form/ModelAttributeForm.tsx
Refs CMDB_INSTANCE-2129
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cmdb实例编辑支持手动验证

- libs/basic-components/src/Sidebar.spec.tsx
- libs/basic-components/src/Sidebar.tsx
> fix(menu): support query in active excludes

- libs/cmdb-instances/src/model-attribute-form-control/ModelAttributeFormControl.tsx
> fix(): 模型属性中，单选枚举型支持显示为树状结构 refs: CMDB_MODEL-345

- libs/charts/src/interfaces/panel.ts
- libs/charts/src/utils/number.spec.ts
- libs/charts/src/utils/number.ts
- libs/charts/src/utils/valueFormatter.spec.ts
- libs/charts/src/utils/valueFormatter.ts
> fix(formatValue): allow disable fixed precision

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
refs: CMDB_INSTANCE-2544
请勾选以下两组选项其中之一：
或者：
>
>
> fix(instance-detail): 修复配置字段在模型中未启用时，无法控制其它属性显隐

- libs/charts/src/utils/dataRate.spec.ts
- libs/charts/src/utils/valueFormatter.spec.ts
- libs/constants/src/units/byteRates.ts
> fix(): data rate units are decimal based

- libs/cmdb-instances/src/cmdb-instances-select-panel/CmdbInstancesSelectPanel.tsx
Refs CMDB_INSTANCE-2566
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support filterInstanceSourceDisabled

- libs/cmdb-instances/src/data-providers/fetchCmdbInstanceDetail.ts
Refs CMDB_CONSUME-849
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 同步后台契约调整ProxyGetInstanceDetail

- libs/cmdb-instances/src/instance-list-table/DisplaySettings.tsx
Closes CMDB_INSTANCE-2605
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 售中工单_CMDB实例列表字段显示问题_Centos7.9_x86

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
- libs/cmdb-instances/src/instance-detail/index.module.css
> fix(): CMDB_INSTANCE-2633 应用系统管理的实例预览详情抽屉的自适应方案优化 ref CMDB_INSTANCE-2633

- .size-limit.js
- libs/cmdb-instances/src/cmdb-instance-select/CmdbInstanceSelect.module.css
- libs/cmdb-instances/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- libs/cmdb-instances/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- libs/cmdb-instances/src/i18n/constants.ts
- libs/cmdb-instances/src/i18n/locales/en.ts
- libs/cmdb-instances/src/i18n/locales/zh.ts
- libs/cmdb-instances/src/index.ts
Closes CD-9390
请勾选以下两组选项其中之一：
或者：
>
>
> feat(CmdbInstanceSelect): Move the CmdbInstanceSelect component here

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
refs: CMDB_INSTANCE-2665
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 图标展示上优化

- libs/cmdb-instances/src/instance-list-drawer/InstanceListDrawer.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
refs: CMDB_INSTANCE-2665
请勾选以下两组选项其中之一：
或者：
>
>
> fix():修复查询指定的关系实例

- libs/cmdb-instances/src/instance-list-drawer/InstanceListDrawer.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.module.css
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list-table/TableTooltip.module.css
- libs/cmdb-instances/src/instance-list-table/TableTooltip.spec.tsx
- libs/cmdb-instances/src/instance-list-table/TableTooltip.tsx
Closes CMDB_INSTANCE-2709
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 查看全部关系实例，应该要展示所有关联的实例；抽屉关闭后，tooltips没有消失，建议优化一下。

- libs/cmdb-instances/src/instance-detail/components/instances-attachment-display/instances-attachment-display.spec.tsx
- libs/cmdb-instances/src/instance-detail/components/instances-attachment-display/instances-attachment-display.tsx
> fix(): cmdb实例详情构件支持查看文件url中带有查询参数的附件属性 ref CMDB_INSTANCE-2756

- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
> fix(): instanceList新增tableConfig属性用于修改表格ui ref CMDB_INSTANCE-2769

- libs/cmdb-instances/src/instance-list-drawer/InstanceListDrawer.tsx
- libs/cmdb-instances/src/instance-list-table/InstanceListTable.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.spec.tsx
- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_INSTANCE-2839
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): CMDB的父模型的通用实例列表无法点击进去实例详情页&实例列表预览关系时，点击实例详情无法跳转

- libs/cmdb-utils/src/cmdbUtil.spec.ts
- libs/cmdb-utils/src/cmdbUtil.ts
Closes MONITOR-9964
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 售中工单_拨测任务-过滤实例的字段包含视图隐藏的字段_centos7.9_x86

- libs/cmdb-instances/src/instance-list-table/AdvancedSearchCondition.tsx
refs: MONITOR-10022
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复国际化丢失的问题

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
refs: CMDB_DISCOVERY-1474
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复extraFixedFields变化没有重新计算 fieldids 值

- libs/cmdb-instances/src/instance-list-modal/InstanceListModal.tsx
> fix():  CMDB_INSTANCE-3148 实例拓扑聚类为列表模式时，提供实例详情的跳转 ref CMDB_INSTANCE-3148

- libs/cmdb-instances/src/instance-list/InstanceList.tsx
Closes CMDB_INSTANCE-3204
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 在cmdb实例，用户自定义显示字段排序不生效

- libs/cmdb-instances/src/instance-detail/InstanceDetail.tsx
> fix(): CMDB_INSTANCE-3076 实例列表可查看与自定义跨级关系  ref CMDB_INSTANCE-3076
